#!/usr/bin/env python3
"""
test_case.py --- LLMTestCase data model shared by metrics, runner, and API

Contains:
    LLMTestCase: immutable data model for one eval case
"""

from dataclasses import dataclass, field, replace


@dataclass(frozen=True)
class LLMTestCase:
    """Immutable data model for one eval case.

    Attributes:
        input: Question or prompt shown to the model under test.
        actual_output: Answer generated by the model under test.
        expected_output: Reference answer, when one exists.
        retrieval_context: Ranked passages retrieved for the input.
        context: Gold reference context for hallucination checks.
        tools_called: Tools the agent invoked, in call order.
        expected_tools: Tools the run was expected to invoke, in order.
        metadata: Free-form per-case annotations (repo, tags, run id).
    """

    input: str
    actual_output: str
    expected_output: str | None = None
    retrieval_context: list[str] = field(default_factory=list)
    context: list[str] = field(default_factory=list)
    tools_called: list[str] = field(default_factory=list)
    expected_tools: list[str] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)

    def tag(self, key: str, value: str) -> "LLMTestCase":
        """Returns a copy with one metadata tag added.

        Args:
            key: Metadata key to set.
            value: Metadata value to store.

        Returns:
            tagged: Case with the metadata entry added.
        """
        metadata = {**self.metadata, key: value}
        return replace(self, metadata=metadata)

    def with_output(self, actual_output: str) -> "LLMTestCase":
        """Returns a copy of the case with a different generated answer.

        Args:
            actual_output: Replacement answer text.

        Returns:
            updated: Case identical except for actual_output.
        """
        return replace(self, actual_output=actual_output)

    def redacted(self) -> "LLMTestCase":
        """Returns a copy with metadata values masked for logging.

        Returns:
            redacted: Case whose metadata values are replaced with "***".
        """
        masked = {key: "***" for key in self.metadata}
        return LLMTestCase(
            input=self.input,
            actual_output=self.actual_output,
            expected_output=self.expected_output,
            retrieval_context=list(self.retrieval_context),
            context=list(self.context),
            tools_called=list(self.tools_called),
            expected_tools=list(self.expected_tools),
            metadata=masked,
        )

    @property
    def is_agent_run(self) -> bool:
        """Reports whether the case represents an agent trajectory.

        Returns:
            is_agent: True when tool expectations or calls are present.
        """
        return bool(self.tools_called or self.expected_tools)

    @staticmethod
    def from_dict(payload: dict) -> "LLMTestCase":
        """Deserializes a case from its API payload.

        Args:
            payload: Mapping produced by to_dict().

        Returns:
            test_case: Reconstructed LLMTestCase.
        """
        return LLMTestCase(**payload)

    def to_dict(self) -> dict:
        """Serializes the case for the results API.

        Returns:
            payload: JSON-safe mapping of all case fields.
        """
        return {
            "input": self.input,
            "actual_output": self.actual_output,
            "expected_output": self.expected_output,
            "retrieval_context": list(self.retrieval_context),
            "context": list(self.context),
            "tools_called": list(self.tools_called),
            "expected_tools": list(self.expected_tools),
            "metadata": dict(self.metadata),
        }

    @property
    def has_expected_output(self) -> bool:
        """Reports whether a reference answer is present.

        Returns:
            has_expected: True when expected_output is set.
        """
        return self.expected_output is not None

    @property
    def is_rag_case(self) -> bool:
        """Reports whether the case carries retrieval context.

        Returns:
            is_rag: True when retrieved passages are present.
        """
        return bool(self.retrieval_context)
