#!/usr/bin/env python3
"""
test_case.py --- LLMTestCase data model shared by metrics, runner, and API

Contains:
    LLMTestCase: immutable data model for one eval case
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class LLMTestCase:
    """Immutable data model for one eval case.

    Attributes:
        input: Question or prompt shown to the model under test.
        actual_output: Answer generated by the model under test.
        expected_output: Reference answer, when one exists.
        retrieval_context: Ranked passages retrieved for the input.
        context: Gold reference context for hallucination checks.
        tools_called: Tools the agent invoked, in call order.
        expected_tools: Tools the run was expected to invoke, in order.
        metadata: Free-form per-case annotations (repo, tags, run id).
    """

    input: str
    actual_output: str
    expected_output: str | None = None
    retrieval_context: list[str] = field(default_factory=list)
    context: list[str] = field(default_factory=list)
    tools_called: list[str] = field(default_factory=list)
    expected_tools: list[str] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)
